version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "irStats"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ccig0t5lmzsg"
s3_prefix = "irStats"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
